### PR TITLE
Basic travis-ci

### PR DESCRIPTION
**Pull request by cristaloleg**

### CODE REVIEW

**Comment by zeebo** [comment]
Just a ping to let you know that I'm working on being able to press merge for this.

**Comment by cristaloleg** [comment]
Pong 👍

**Comment by jtolds** [comment]
Sorry, I'm the hold up. This code isn't Apache licensed, which means we need a bit more legal legwork around copyright and accepting pull requests. I'll get back after I've sorted out with legal if we need a contributor license agreement or not.

**Comment by zeebo** [comment]
This is so trivial that I’m just going to go ahead. Sorry about the wait. :(

**Comment by cristaloleg** [comment]
Oh, thanks :D 
BTW, it's already 2 version behind the newest 😉

**Pull request merged**
